workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^(\[Draft\]|\(Draft\)|Draft:)/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never

stages:
  - test
  - github_push

variables:
  GIT_SUBMODULE_STRATEGY: normal

.github_push:
  rule:
    if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    when: always
    when: never
  script: 
    eval $(ssh-agent -s)
    echo "$SSH_KEY_GITHUB_ACCESS" | tr -d '\r' | ssh-add - > /dev/null
    ssh-add -L
    git push --repo=git@github.com:MDG-Graphics/mili --force



.slurm-defaults:
  variables:
    NNODES: 1
    NPROCS: 16
    QUEUE: pdebug
    INTEG_WALL_TIME: 5

.slurm:
  variables:
    LLNL_SLURM_SCHEDULER_PARAMETERS: "-N $NNODES -n $NPROCS -p $QUEUE -t $INTEG_WALL_TIME"

.build-mili-xmilics:
  variables:
    BUILD_SPEC: ${SYS_TYPE}-${COMPILER_SPEC}
  script:
    - configure.py -hc host-configs/toss_3_x86_64_ib-intel@2021.4.cmake -bt RelWithDebInfo
    - cd build-${BUILD_SPEC}-relwithdebinfo
    - make -j
    - cd -

.run-tests:
  script:
    - cd test/
    - mdgtest/Test.py -e mililib_env -c ../build-${BUILD_SPEC}-relwithdebinfo/lib -I ../build-${BUILD_SPEC}-relwithdebinfo/include -n1 -p1 -s all > test_mili.out
    - num_mili_failed=$( grep -c -e failed -e "did not run correctly" test_mili.out ) || true
    - mdgtest/Test.py -e xmilics_env -c ../build-${BUILD_SPEC}-relwithdebinfo/bin/xmilics -n1 -p1 -s all > test_xmilics.out
    - num_xmilics_failed=$( grep -c -e failed -e "did not run correctly" test_xmilics.out ) || true
    - num_failed=$(( $num_mili_failed + $num_xmilics_failed ))
    - exit $num_failed

.toss3:
  variables:
    SYS_TYPE: toss_3_x86_64_ib

.toss3-intel:
  extends: .toss3
  variables:
    COMPILER_SPEC: intel@2021.4
  before_script:
    - module load intel/2021.4
    - module load python/3.7.2

toss3_intel_slurm_mili:
  stage: test
  tags:
    - rzgenie
    - slurm
    - batch
  extends:
    - .toss3-intel
    - .slurm-defaults
    - .slurm
    - .build-mili-xmilics
  script:
    - !reference [ .build-mili-xmilics, script ]
    - !reference [ .run-tests, script ]
