# $Id: Makefile.Tests,v 1.15 2021/09/17 23:07:16 jdurren Exp $

srcdir= @srcdir@
abs_srcdir= @abs_srcdir@
top_srcdir= @top_srcdir@
abs_top_srcdir= @abs_top_srcdir@
builddir= @builddir@
abs_builddir= @abs_builddir@
top_builddir= @top_builddir@
abs_top_builddir= @abs_top_builddir@
VPATH = @srcdir@:@top_srcdir@/src:@srcdir@/data

MILI_VERSION = @MILI_VERSION@

OS_NAME    = @OS_NAME@
SHELL      = @SHELL@
SHELL_ARGS = @SHELL_ARGS@

CC = @CC@
FC = @F77@

CC_FLAGS = @CC_FLAGS_DEBUG@
FC_FLAGS = @FC_FLAGS_DEBUG@

#
# To run "mode_test" app, first add "-DMODE_TEST" to CPPFLAGS
# then compile mode_test target.
#

# Suffix rule to create the object files.
# rules to automatically generate dependency makefiles
.SUFFIXES :
                                                                                  
%.o: %.c
	$(PURIFY_CMD) $(CC) $(CC_FLAGS) $(CPPFLAGS) $(MILIINCPATH) -c $<
                                                                                  
%.o: %.f
	$(PURIFY_CMD) $(FC) $(FC_FLAGS) $(CPPFLAGS) $(MILIINCPATH) -c $<
                                                                                  
%.o: %.F
	$(PURIFY_CMD) $(FC) $(FC_FLAGS) $(CPPFLAGS) $(MILIINCPATH) -c $<
                                                                                  


# Set to location of MILI includes and library
ROOT_DIR	= @ROOT_DIR@
MILIHOME	= @MILI_HOME@
MILIINCPATH	= -I$(ROOT_DIR)/include
MILILIBPATH	= -L$(ROOT_DIR)/@LIBDEBUG_PATH@
MILI_LIB        = @MILI_LIB@
TAURUS_LIB      = @TAURUS_LIB@
EPRTF_LIB       = @EPRTF_LIB@
BINTEST_PATH=@BINTEST_PATH@

CDEMOS = \
        del_test \
        del_test2_p \
        del_test2_s \
        mixdb \
        mode_test \
        titest \
	    MiliDiff \
        value_change \
        restart \
		restart_zero \
		diablo_restart
 
FDEMOS = \
        GenFaceDB \
        dbftest \
        hexdb \
        hexdb2 \
        hexdb2p2 \
        hvadb \
        multfmt \
        nodev1 \
        partdb \
        partdb2 \
        partre \
        partre_b \
        partre_c \
        partre_d \
        partre_e \
        qmenu \
        qnost \
        quaddb \
        shelldb \
        shellrw \
        shellrw_b \
        shellrw_c \
        surfdb \
        tridb \
	timedepStringdb

DEMOS = ${CDEMOS} ${FDEMOS}

AFILES = \
    ftA hex2oA hexoA hex2p2oA hvaoA part2dA partoA premptA prestA qmenuoA \
    qnstA quadoA shelloA shrwA trioA multoA nv1oA mixoA vec_arrayA

tests: ${CDEMOS} ${FDEMOS}

db: ${AFILES}

militest: ${AFILES}

# On Linux, use: ${FDEMOS}: %: %.o
# ${FDEMOS}: $$@.o

${FDEMOS}: %: %.o
	${FC} -o $@ ${FC_FLAGS} ${MILIINCPATH} $@.o ${MILILIBPATH} -lmili
	mv $@.o ../objs_test
	mv $@ ../$(BINTEST_PATH)

# On Linux, use: ${CDEMOS}: %: %.o
# ${CDEMOS}: $$@.o

${CDEMOS}: %: %.o
	${CC} -o $@ ${CC_FLAGS} ${MILIINCPATH} $@.o ${MILILIBPATH} -lmili -ltaurus
	mv $@.o ../objs_test
	mv $@ ../$(BINTEST_PATH)
    
# -lefence

ftA: dbftest data
	./dbftest
    
hexoA: hexdb data
	./hexdb
    
hex2oA: hexdb2 data
	./hexdb2
    
hex2p2oA: hexdb2p2 data
	./hexdb2p2
    
hvaoA: hvadb data
	./hvadb
    
part2dA: partdb2 data
	./partdb2
    
partoA: partdb data
	./partdb
    
prestA: partre partre_b partre_c data
	./partre
	./partre_b
	./partre_c
    
premptA: partre_d partre_e data
	./partre_d
	./partre_e
    
qmenuoA: qmenu data
	./qmenu
    
qnstA: qnost data
	./qnost
    
quadoA: quaddb data
	./quaddb
    
shelloA: shelldb data
	./shelldb
    
shrwA: shellrw shellrw_b shellrw_c data
	./shellrw
	./shellrw_b
	./shellrw_c
    
trioA: tridb data
	./tridb
    
multoA: multfmt data
	./multfmt
    
nv1oA: nodev1 data
	./nodev1
    
mixoA: mixdb data
	./mixdb

vec_arrayA: vec_array data
	./vec_array

${MLIB}: ${MILI_C_SRC} ${MILI_f_SRC} ${MILI_F_SRC}
	cd ${top_srcdir}/src && ${MAKE}
data:
	mkdir ${srcdir}/data

mostlyclean: clean

distclean: clean
	rm Makefile

clean: clean_obj clean_app clean_db

clean_obj:
	rm -f *.o

clean_app:
	rm -f ${DEMOS}

clean_db:
	rm -rf data

install uninstall:

