#!/bin/ksh

# $Id: F_make,v 1.2 2002/12/11 22:16:22 speck Exp $
# 
# This work was produced at the University of California, Lawrence 
# Livermore National Laboratory (UC LLNL) under contract no. 
# W-7405-ENG-48 (Contract 48) between the U.S. Department of Energy 
# (DOE) and The Regents of the University of California (University) 
# for the operation of UC LLNL. Copyright is reserved to the University 
# for purposes of controlled dissemination, commercialization through 
# formal licensing, or other disposition under terms of Contract 48; 
# DOE policies, regulations and orders; and U.S. statutes. The rights 
# of the Federal Government are reserved under Contract 48 subject to 
# the restrictions agreed upon by the DOE and University as allowed 
# under DOE Acquisition Letter 97-1.
# 
# 
# DISCLAIMER
# 
# This work was prepared as an account of work sponsored by an agency 
# of the United States Government. Neither the United States Government 
# nor the University of California nor any of their employees, makes 
# any warranty, express or implied, or assumes any liability or 
# responsibility for the accuracy, completeness, or usefulness of any 
# information, apparatus, product, or process disclosed, or represents 
# that its use would not infringe privately-owned rights.  Reference 
# herein to any specific commercial products, process, or service by 
# trade name, trademark, manufacturer or otherwise does not necessarily 
# constitute or imply its endorsement, recommendation, or favoring by 
# the United States Government or the University of California. The 
# views and opinions of authors expressed herein do not necessarily 
# state or reflect those of the United States Government or the 
# University of California, and shall not be used for advertising or 
# product endorsement purposes.
#

if test ! -d FOR_tmp; then
    echo "Moving .f files into directory FOR_tmp";
    mkdir FOR_tmp;
    mv *.f FOR_tmp;
# else
# # Update stored .f files that have changed since first checkout.
#     for f_file in *.f; do
#         if test -a FOR_tmp/$f_file; then
#             diffs=`diff $f_file FOR_tmp/$f_file | wc -c`;
#             if [[ $diffs -ne 0 ] && [ test $f_file -nt FOR_tmp/$f_file ]]; then
#                 mv -f $f_file FOR_tmp;
#             fi;
#         fi;
#     done;
fi

if test -r FOR_tmp/*.f; then
    for f_file in FOR_tmp/*.f; do
        F_file=`basename $f_file .f`.F;
        if [ ! -a "$F_file" ]; then
            echo "Creating $F_file from $f_file";
            cp $f_file $F_file;
        else
            diffs=`diff $f_file $F_file | wc -c`;
            if [ $diffs -ne 0 ]; then
                echo "  $F_file exists, differs from $f_file";
            fi;
        fi;
    done;
fi



