#! /usr/local/bin/python

import sys,string,os,math,fpformat,popen2
from string import Template
from  dyna_env import *


cur_driver = parallel_drivers[par_system]

default_tolerance = 1.0e-04
default_tol_type = "rel"
# define any additional suite combinations
# define as follows:
#
#  "suite_name" = ["testname[0]",...,"testname[n]"],
#  "next_suite" = ...
#  There must be a comma between each suite declaration
#  Do not use 'all' or a suite name from mapping they will be ignored

defined_suites ={"count_regular" : {"COUNT":["d3samp1",  "d3samp3",  "d3samp6",  "d3samp7",
                                             "d3samp8",  "d3samp9",  "d3samp10", "d3samp17",
                                             "d3samp18", "d3samp19", "d3samp20", "d3samp22",
                                             "d3snd1",   "d3snd1d",   "d3snd4",   "sbi",      "sbp",
                                             "nrbc_norm", "nrbc_shear"]},
                 "count_long" :{"COUNT":["d3snd2", "d3snd2d", "d3snd3", "d3snd3n", "d3snd3d", "d3snd5",  "d3snd6","d3samp2",  
                                         "d3samp4","d3samp5","d3samp21","mk24"]},
                 "test" :{"BAR":["bar1","bar1_9"],
                          "BEAM": ["vrt_HL0","bending-24"],
                          "PLATE":["plate3"],
                          "SLIDE":["sslide9ps", "sslide9pt", "sslide10lr"]},
			   "bad_bar": {"BAR": ["bar62"]},
                 "smoke":{}
                }

###############################################################################################
#
#  This is the default mapping of the tests to the required information for running them
#  It has the following layout
#
#  mapping = {"suite_name":"quicklist":["test1","test2",....,"testn"],##used for quick validation of
#                                                                       test suite combo
#                          "file_suffix":"suffix for the file read in by dyna3d/paradyn",
#                          "tests": None | a dictionary of tests which do not use the suite defaults
#                          "awkfiles": ["awkfile1", "awkfile2", ...]  list of all the awk files needed
#                                                                     to post process the run
#                          "awk_commands":  this is an array of python Templates which can include the
#                                           variable substitution strings
#                                           ${preawk}(prefix for awk in case of SunOS is 'n'), 
#                                           ${sig}(significant digits) and ${prob}(test name)
#                          "exec command": command to use when executing dyna/paradyn. It does the 
#                                          following variable substitution
#                                          $CODE = name of code
#                                          ${prob} = test name
#                          "default_tolerance": unused at this point
#                          "test_type": The test type to assign to this test absolute,image, smoke...
#
# Generic suite
# "suite_name":"quicklist":[""],
#              "file_suffix":".dyn",
#              "tests": None,
#              "awkfiles": [""],
#              "awk_commands": [Template("${preawk}awk -f XXX.awk -v sig_dig=${sig} ${prob}.hsp")],
#              "exec command": [Template("$CODE i=${prob}.dyn ")],
#              "default_tolerance": {"type":"rel","tolerance":"0.0"}
###############################################################################################
mapping = {"BAR":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                  "keep_on_pass_file_expr":["answ",".dyn"], 
                  "quicklist":["bar1_2", "bar1",     "bar1_4", "bar1_5", "bar1_6", "bar1_7", "bar1_7v",
                               "bar1_7vs", "bar1_8", "bar1_8v","bar1_9", "bar1_9v","bar1_10","bar1_10v",
                               "bar1_10vs","bar1_12",
                               "bar2",   "bar2_10s", "bar2_10v",
                               "bar3",   "bar4",     "bar5",   "bar6",   "bar7",   "bar8",    "bar9",
                               "bar10",  "bar10_leos", "bar10_eos5", 
                               "bar11",  "bar12",    "bar13",  "bar14",
                               "bar15",  "bar15_CDF","bar16",  "bar17", "bar18", "bar19", "bar21",
                               "bar22",  "bar23",    "bar24",  "bar25", "bar26", "bar27", "bar31", "bar32",
                               "bar33",  "bar35",    "bar36",  "bar38", "bar39", "bar40", "bar43", "bar44",
                               "bar45",  "bar46",    "bar49",  "bar53", "bar52", "bar54", "bar55",
                               "bar56",  "bar56_9s", "bar56_9v", "bar56_9vs",
                               "bar59",  "bar60",    "bar62",  "bar63", "bar64", "bar65", "bar66", "bar67",
                               "bar69",  "bar70",    "bar71",  "bar72", "bar73", "bar74"],
                  "file_suffix":".dyn",
                  "baseline_suffix":"answ",
                  "test_output_suffix":"jansw",
                  "tests":None,
                  "run_validation_suffix":".hsp",
                  "awkfiles":["bar.awk"],
                  "awk_commands": [Template("${preawk}awk -f bar.awk -v sig_dig=${sig} ${prob}.hsp")],
                  "exec_command":[Template("$CODE i=${prob}.dyn ")],
                  "default_tolerance":{"type":"rel","tolerance":"1.0e-03"}
                  },
           "BASIC":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                    "keep_on_pass_file_expr":["answ",".dyn"], 
                    "quicklist":["basic1" ,"basic2"  ,"basic2i" ,"basic7"  ,"basic21","basic21i",
                                 "basic23","basic23i", "basic27","basic43i","basic46","basic46i",
                                 "basic63"],
                    "file_suffix":".dyn",
                    "tests":None,
                    "run_validation_suffix":".hsp",
                    "awkfiles":["basic.awk"],
                    "awk_commands": [Template("${preawk}awk -f basic.awk -v sig_dig=${sig} ${prob}.hsp")],
                    "exec_command":[Template("$CODE i=${prob}.dyn ")],
                    "default_tolerance":{"type":"rel", "tolerance":"5.0e-04"}
                   },
           "BEAM":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                   "keep_on_pass_file_expr":["answ",".dyn"], 
                   "quicklist":["vrt_BS",   "vrt_HL0", "vrt_HL2",  "vrt_HL3", "vrt_HL4",   "vrt_HL5",
                                "HL2-mat1", "HL2-mat1o","HL2-mat3","HL2-mat24", "HL2-mat54","HL2-mat71",
                                "BS-mat1",  "BS-mat1o","BS-mat3", "BS-mat28",
                                "beam_udi",
                                "truss1", "truss3", "truss24", "truss54", "truss71",
                                "truss3pl", "truss24pl", "truss54pl", "truss71pl",
                                "tension-3", "tension-24", "tension-54", "tension-71",
                                "bending-3", "bending-24", "bending-54", "bending-71",
                                "torque-3", "torque-24", "torque-54", "torque-71"],
                   "file_suffix":".dyn",
                   "run_validation_suffix":".hsp",
                   "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                   "awkfiles":["vrt.awk1","vrt.awk2"],
                   "awk_commands": [Template("${preawk}awk -f vrt.awk1 -v sig_dig=${sig} ${prob}.hsp"),
                                    Template("${preawk}awk -f vrt.awk2 -v sig_dig=${sig} ${prob}.velfor")],
                   "exec_command":[Template("$CODE i=${prob}.dyn ")],
                   "tests":{"bending-3":{"awkfiles":["bending-3.awk"],
                                         "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "bending-24":{"awkfiles":["bending-24.awk"],
                                          "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "bending-54":{"awkfiles":["bending-54.awk"],
                                          "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "bending-71":{"awkfiles":["bending-71.awk"],
                                          "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "beam_udi":{"awkfiles":["beam_udi.awk"],
                                          "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "tension-3":{"awkfiles":["tension-3.awk"],
                                         "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "tension-24":{"awkfiles":["tension-24.awk"],
                                          "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "tension-54":{"awkfiles":["tension-54.awk"],
                                          "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "tension-71":{"awkfiles":["tension-71.awk"],
                                          "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "torque-3":{"awkfiles":["torque-3.awk"],
                                        "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "torque-24":{"awkfiles":["torque-24.awk"],
                                         "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "torque-54":{"awkfiles":["torque-54.awk"],
                                         "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "torque-71":{"awkfiles":["torque-71.awk"],
                                         "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "truss3":{"awkfiles":["truss3.awk"],
                                      "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "truss24":{"awkfiles":["truss24.awk"],
                                       "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "truss54":{"awkfiles":["truss54.awk"],
                                       "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "truss71":{"awkfiles":["truss71.awk"],
                                       "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "truss1":{"awkfiles":["truss1.awk"],
                                      "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "truss3pl":{"awkfiles":["truss3pl.awk"],
                                        "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "truss24pl":{"awkfiles":["truss24pl.awk"],
                                         "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "truss54pl":{"awkfiles":["truss54pl.awk"],
                                         "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "truss71pl":{"awkfiles":["truss71pl.awk"],
                                         "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]}
                           }
                  },
           "COUNT":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                    "keep_on_pass_file_expr":["answ",".dyn"], 
	            "quicklist":["al_sph_rod",  "airbag1",     "ang_vel",
                                 "base_acc",    "constraint1", "constraint2", "csf",         "cohesive1", 
                                 "d3samp1",     "d3samp2",     "d3samp3",     "d3samp3a",    "d3samp4",
                                 "d3samp5a",    "d3samp5",     "d3samp6",     "d3samp6_no_cc",
                                 "d3samp7",     "d3samp8",     "d3samp9",     "d3samp10",    "d3samp17",
                                 "d3samp18",    "d3samp19",    "d3samp20",    "d3samp21",    "d3samp22",
                                 "d3self1",     "delam1",      "det_pts",     "discrete",    "discrete3d",
                                 "dr_bar",      "dr_bar_e",    "dr_bar_e1",   "drill1",      "es_bfl",      
				 "fdamp1",      "fdamp2",      "fdamp3",      "fdamp4",      "fdamp5",
				 "fdamp6",      "gravity_init","isave1",      "init_cond1",  "init_cond2",
                                 "kingery_hemi","kingery_sphere",             "leos_sph_rod","m10eos13",
                                 "m64eos17",    "m68eos16a",   "m68eos16b",   "max_press",   "mk24",
                                 "mk27",        "mk54",        "mk71",        "mk73",        "mk74",
                                 "m52_plate",   "mom_dep",     "moving_wall",
                                 "nrbc_norm",   "nrbc_shear",  "one_d_slide", "piston",
                                 "press_type5", "press_type6", "press_type7", "rbeam_n_box",
                                 "rbm_shell",   "rb_switch",   "rig_wall1",   "rig_wall2",   "rigid_body1",
                                 "rigid_body2", "rigid_body3", "rigid_body4", "rot_init1",   "rot_init2",
                                 "sbi",         "sbp",         "shear_trac1", "shear_trac2", "shear_trac3",
                                 "shm15",       "spc",         "spf",         "sph_box",     "sym_plane1",
                                 "tbssl1",      "tbssl2",      "thermal1",    "thermal2",    "thermal3", "tnswf"],
                    "file_suffix":".dyn",
                    "run_validation_suffix":".hsp",
                    "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                    "awkfiles":["${prob}.awk"],
                    "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")],
                    "exec_command":[Template("$CODE i=${prob}.dyn ")],
                    "tests":{"cohesive1":{"awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.velfor")]},
                             "delam1":{"awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.velfor")]},
                             "dr_bar":{"required_files":["dr_bar.elem"]},
                             "dr_bar_e":{"required_files":["dr_bar_e.elem"]},
                             "d3samp6_no_cc":{"required_files":["d3samp6_no_cc_keywords","d3samp6_no_cc_size",
                                              "d3samp6_no_cc_nodes","d3samp6_no_cc_bricks","d3samp6_no_cc_beams",
                                              "d3samp6_no_cc_shells","d3samp6_no_cc_mats"]},
                             "max_press":{"awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.mpres")]},
                             "fdamp1":{"awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.velfor")]},
                             "fdamp2":{"awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.velfor")]},
                             "fdamp3":{"awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.velfor")]},
                             "fdamp4":{"awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.velfor")]},
                             "fdamp5":{"awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.velfor")]},
                             "fdamp6":{"awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.velfor")]},
                             "thermal3":{"required_files":["thermal3_topaz_plt00","thermal3_topaz_pltA"]},
                             "isave1":{"required_files":["isave1a.dyn","isave1a.dyn.8"],
                                       "exec_command":[Template("$CODE i=${prob}a.dyn "),
                                                       Template("$CODE i=${prob}.dyn")]}
                            }
                   },
           "DAMP":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                   "keep_on_pass_file_expr":["answ",".dyn"], 
	           "quicklist":["stiffd_bar",        "stiffd_bar1",      "stiffd_bar2",
                                "stiffd_beam_bs1",   "stiffd_beam_hl1",  "stiffd_beam_tr1", 
                                "stiffd_beam_bs2",   "stiffd_beam_hl2",  "stiffd_beam_tr2", 
                                "stiffd_shell_blt1", "stiffd_shell_hl1",
                                "stiffd_shell_blt2", "stiffd_shell_hl2",
                                "stiffd_tplate1",    "mplate1"],
                    "file_suffix":".dyn",
                    "run_validation_suffix":".hsp",
                    "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                    "awkfiles":["${prob}.awk"],
                    "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")],
                    "exec_command":[Template("$CODE i=${prob}.dyn ")],
                    "tests":{"stiffd_beam_hl1":{"awkfiles":["stiffd_beam.awk1","stiffd_beam.awk2"],
                                                "awk_commands": [Template("${preawk}awk -f stiffd_beam.awk1 -v sig_dig=${sig} ${prob}.hsp"),
                                                                 Template("${preawk}awk -f stiffd_beam.awk2 -v sig_dig=${sig} ${prob}.velfor")]},
                             "stiffd_beam_bs1":{"awkfiles":["stiffd_beam.awk1","stiffd_beam.awk2"],
                                                "awk_commands": [Template("${preawk}awk -f stiffd_beam.awk1 -v sig_dig=${sig} ${prob}.hsp"),
                                                                 Template("${preawk}awk -f stiffd_beam.awk2 -v sig_dig=${sig} ${prob}.velfor")]}, 
                             "stiffd_beam_hl2":{"awkfiles":["stiffd_beam.awk1","stiffd_beam.awk2"],
                                                "awk_commands": [Template("${preawk}awk -f stiffd_beam.awk1 -v sig_dig=${sig} ${prob}.hsp"),
                                                                 Template("${preawk}awk -f stiffd_beam.awk2 -v sig_dig=${sig} ${prob}.velfor")]},
                             "stiffd_beam_bs2":{"awkfiles":["stiffd_beam.awk1","stiffd_beam.awk2"],
                                                "awk_commands": [Template("${preawk}awk -f stiffd_beam.awk1 -v sig_dig=${sig} ${prob}.hsp"),
                                                                 Template("${preawk}awk -f stiffd_beam.awk2 -v sig_dig=${sig} ${prob}.velfor")]}
                            }
                   },
           "DEGEN":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                   "keep_on_pass_file_expr":["answ",".dyn"],
                   "quicklist":["dprism", "dtetra", "dtshell"],
                   "file_suffix":".dyn",
                   "run_validation_suffix":".hsp",
                   "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                   "tests":None,
                   "awkfiles":["${prob}.awk"],
                   "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")],
                   "exec_command":[Template("$CODE i=${prob}.dyn ")]
                   },
           "EOS":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                  "keep_on_pass_file_expr":["answ",".dyn"],
                  "quicklist":["brickm9eos3","brickm9eos6","brickm9eos6_e", "brickm9eos9", "brickm9eos11"],
                  "file_suffix":".dyn",
                  "baseline_suffix":"answ",
                  "test_output_suffix":"jansw",
                  "tests":None,
                  "run_validation_suffix":".hsp",
                  "awkfiles":["eos.awk"],
                  "awk_commands": [Template("${preawk}awk -f eos.awk -v sig_dig=${sig} ${prob}.hsp")],
                  "exec_command":[Template("$CODE i=${prob}.dyn ")],
                  "default_tolerance":{"type":"rel","tolerance":"1.0e-03"}
                  },
           "HOURGLASS":{"keep_on_fail_file_expr":["hsp", "plt",".dyn"],
                    "keep_on_pass_file_expr":["answ",".dyn"], 
	            "quicklist":["s_wmode_s",  "s_wmode_v",     "s_wmode_vs",
                                 "s_xbmode_s",  "s_xbmode_v",     "s_xbmode_vs",
                                 "s_xmmode_s",  "s_xmmode_v",     "s_xmmode_vs"],
                    "file_suffix":".dyn",
                    "run_validation_suffix":".hsp",
                    "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                    "awkfiles":["${prob}.awk"],
                    "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")],
                    "exec_command":[Template("$CODE i=${prob}.dyn ")],
                    "tests":None
                   },
           "MASS_AUG":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                       "keep_on_pass_file_expr":["answ",".dyn"], 
                       "quicklist":["ma_beam_hl",    "ma_beam_bs",     "ma_beam_tr",
                                    "ma_plate_blt4", "ma_plate_mbwc",  "ma_plate_mbwc4",
                                    "ma_plate_blt",  "ma_plate_hl",    "ma_plate_mem", 
                                    "ma_plate_yase", "ma_plate_hl4",
                                    "ma_shell_bciz", "ma_shell_blt28", "ma_shell_c0",
                                    "ma_shell_y28" , "ma_bar3"],
                       "file_suffix":".dyn",
                       "run_validation_suffix":".hsp",
                       "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                       "awkfiles":["ma_plate.awk"],
                       "awk_commands":[Template("${preawk}awk -f ma_plate.awk -v sig_dig=${sig} ${prob}.hsp")],
                       "exec_command":[Template("$CODE i=${prob}.dyn ")],
                       "tests":{"ma_beam_hl":{"awkfiles":["ma_beam.awk1","ma_beam.awk2"],
                                              "awk_commands": [Template("${preawk}awk -f ma_beam.awk1 -v sig_dig=${sig} ${prob}.hsp"),
                                                               Template("${preawk}awk -f ma_beam.awk2 -v sig_dig=${sig} ${prob}.velfor")]},
                                "ma_beam_bs":{"awkfiles":["ma_beam.awk1","ma_beam.awk2"],
                                              "awk_commands": [Template("${preawk}awk -f ma_beam.awk1 -v sig_dig=${sig} ${prob}.hsp"),
                                                               Template("${preawk}awk -f ma_beam.awk2 -v sig_dig=${sig} ${prob}.velfor")]}, 
                                "ma_beam_tr":{"awkfiles":["ma_beam_tr.awk"],
                                              "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]},
                                "ma_shell_bciz":{"awkfiles":["ma_shell.awk","ma_shell_bciz.awk"],
                                                 "awk_commands":[Template("echo " " | ${preawk}awk  -f ma_shell.awk -v sig_dig=${sig} -f ${prob}.awk ")]},				      					     
                                "ma_shell_blt28":{"awkfiles":["ma_shell.awk","ma_shell_blt28.awk"],
                                                  "awk_commands":[Template("echo " " | ${preawk}awk  -f ma_shell.awk -v sig_dig=${sig} -f ${prob}.awk ")]},					     
                                "ma_shell_c0":{"awkfiles":["ma_shell.awk","ma_shell_c0.awk"],
                                               "awk_commands":[Template("echo " " | ${preawk}awk  -f ma_shell.awk -v sig_dig=${sig} -f ${prob}.awk ")]},					     
                                "ma_shell_y28":{"awkfiles":["ma_shell.awk","ma_shell_y28.awk"],
                                                "awk_commands":[Template("echo " " | ${preawk}awk  -f ma_shell.awk -v sig_dig=${sig} -f ${prob}.awk ")]},
                                "ma_bar3":{"awkfiles":["ma_bar3.awk"],
                                           "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")]}
                               }
                      },
           "ML":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                 "keep_on_pass_file_expr":["answ",".dyn"], 
                 "quicklist":["ml40", "ml41", "ml41u", "ml41u_full", "ml42", "ml43"],
                 "file_suffix":".dyn",
                 "run_validation_suffix":".hsp",
                 "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                 "awkfiles":["${prob}.awk"],
                 "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")],
                 "exec_command":[Template("$CODE i=${prob}.dyn ")],
                 "tests":None,
                   },
           "MMD":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                  "keep_on_pass_file_expr":["answ",".dyn"], 
                  "quicklist":["mmd_s1","mmd_s3","mmd_h1","mmd_h3"],
                  "file_suffix":".dyn",
                  "no_partition":None,
                  "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                  "tests":None,
                  "run_validation_suffix":".hsp",
                  "awkfiles":["${prob}.awk"],
                  "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.mmd")],
                  "exec_command":[Template("$CODE i=${prob}.dyn ")]
                 },
           "NTET":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                   "keep_on_pass_file_expr":["answ",".dyn"], 
                   "quicklist":["ntet20", "ntet20s", "ntet21", "ntet21s", "ntet22", "ntet22s",
                                "ntet23", "ntet23s"],
                   "file_suffix":".dyn",
                   "run_validation_suffix":".hsp",
                   "awkfiles":["ntet.awk","ntets.awk"],
                   "awk_commands": [Template("${preawk}awk -f ntet.awk -v sig_dig=${sig} ${prob}.hsp")],
                   "exec_command":[Template("$CODE i=${prob}.dyn ")],
		   "tests":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                            "keep_on_pass_file_expr":["answ",".dyn"], 
	                    "ntet20":{"awkfiles":["ntet.awk"],
                                      "awk_commands":[Template("${preawk}awk -f ntet.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "ntet21":{"awkfiles":["ntet.awk"],
                                      "awk_commands":[Template("${preawk}awk -f ntet.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "ntet22":{"awkfiles":["ntet.awk"],
                                      "awk_commands":[Template("${preawk}awk -f ntet.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "ntet23":{"awkfiles":["ntet.awk"],
                                      "awk_commands":[Template("${preawk}awk -f ntet.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "ntet20s":{"awkfiles":["ntets.awk"],
                                      "awk_commands":[Template("${preawk}awk -f ntets.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "ntet21s":{"awkfiles":["ntets.awk"],
                                      "awk_commands":[Template("${preawk}awk -f ntets.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "ntet22s":{"awkfiles":["ntets.awk"],
                                      "awk_commands":[Template("${preawk}awk -f ntets.awk -v sig_dig=${sig} ${prob}.hsp")]},
                            "ntet23s":{"awkfiles":["ntets.awk"],
                                      "awk_commands":[Template("${preawk}awk -f ntets.awk -v sig_dig=${sig} ${prob}.hsp")]},
                           },
                  "default_tolerance":{"type":"rel","tolerance":"1.0e-03"}
                  },
           "PLATE":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                    "keep_on_pass_file_expr":["answ",".dyn"], 
	            "quicklist":["plate_bciz", "plate_bciz_rs",
                                 "plate_blt",  "plate_blt_rs", "plate_blt4", "plate_blt4_rs",
                                 "plate_c0",   "plate_c0_rs",  "plate_hl",   "plate_hl_rs",
                                 "plate_hl4",  "plate_hl4_rs",
                                 "plate_mbwc", "plate_mbwc_rs","plate_mbwc4","plate_mbwc4_rs",
                                 "plate_mem",
                                 "plate_yase", "plate_yase_rs",
                                 "plate1",     "plate2",       "plate2i",    "plate3",
                                 "plate4",
                                 "plate12",    "plate15",      "plate18",    "plate19",
                                 "plate21i",   "plate21",      "plate22i",   "plate22",
                                 "plate23",    "plate23i",     "plate24",    "plate28",
                                 "plate30",    "plate33i",     "plate33",    "plate34",
                                 "plate35",
                                 "plate38",    "plate39",      "plate41",    "plate42",
                                 "plate46i",   "plate46",      "plate52",    "plate54",
                                 "plate71",    "plate74",      "plate74i"],
                    "file_suffix":".dyn",
                    "run_validation_suffix":".hsp",
                    "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                    "awkfiles":["plate.awk"],
                    "awk_commands":[Template("${preawk}awk -f plate.awk -v sig_dig=${sig} ${prob}.hsp")],
                    "exec_command":[Template("$CODE i=${prob}.dyn ")],
                    "tests":None
                   },
           "REDEFINE":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                      "keep_on_pass_file_expr":["answ",".dyn"], 
                      "quicklist":["cplate3_newlc"],
                      "file_suffix":".dyn",
                      "run_validation_suffix":".hsp",
                      "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                      "tests":None,
                      "awkfiles":["${prob}.awk"],
                      "required_files":["cplate3_newlc_rst.dyn"],
                      "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")],
                      "exec_command":[Template("$CODE i=${prob}.dyn "),
                                      Template("$CODE c=${prob}.lastdump i=cplate3_newlc_rst.dyn")]
                   },
           "RESTART":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                      "keep_on_pass_file_expr":["answ",".dyn"], 
	              "quicklist":["bar1", "bending-3", "plate1", "torque-3",  "truss1"],
                      "file_suffix":".dyn",
                      "run_validation_suffix":".hsp",
                      "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                      "tests":{"bar1":{"alt_base":{"suite":"BAR","baseline":"bar1"},
                                       "awk_dir":"BAR",
                                       "awkfiles":["bar.awk"],
                                       "awk_commands":[Template("${preawk}awk -f bar.awk -v sig_dig=${sig} ${prob}.hsp")],},

                               "bending-3":{"alt_base":{"suite":"BEAM","baseline":"bending-3"},
                                            "awk_dir":"BEAM"},

                               "plate1":{"alt_base":{"suite":"PLATE","baseline":"plate1"},
                                         "awk_dir":"PLATE",
                                         "awkfiles":["plate.awk"],
                                         "awk_commands":[Template("${preawk}awk -f plate.awk -v sig_dig=${sig} ${prob}.hsp")],},

                               "torque-3":{"alt_base":{"suite":"BEAM","baseline":"torque-3"},
                                           "awk_dir":"BEAM"},

                               "truss1":{"alt_base":{"suite":"BEAM","baseline":"truss1"},
                                         "awk_dir":"BEAM"},
                                  },
                      "awkfiles":["${prob}.awk"],
                      "required_files":["again.dyn"],
                      "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")],
                      "exec_command":[Template("$CODE i=${prob}.dyn "),
                                      Template("$CODE c=${prob}.lastdump i=again.dyn")]
                   },
           "SAND":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                   "keep_on_pass_file_expr":["answ",".dyn"], 
	           "quicklist":["d3snd1", "d3snd1d", "d3snd1_mfric", "d3sndts1",
                                "d3snd2", "d3snd2d", "d3snd2_cyl",   "d3snd2_ignore",
                                "d3snd3", "d3snd3n", "d3snd3d",
                                "d3snd4", "d3snd4box",
                                "d3snd5",
                                "d3snd6", "d3snd6d"],
                   "file_suffix":".dyn",
                   "run_validation_suffix":".hsp",
                   "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                   "awkfiles":["${prob}.awk"],
                   "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")],
                   "exec_command":[Template("$CODE i=${prob}.dyn ")],
                   "tests":None
                   },
           "SHELL":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                    "keep_on_pass_file_expr":["answ",".dyn"], 
	            "quicklist":["BCIZ_2g", "BCIZ_5t", "BCIZ_2u", "BCIZ_2g_rs",
                                 "BLT_2gc", "BLT_2gs", "BLT_2gv", "BLT_2uv",  "BLT_3gv",  "BLT_4gv", 
                                 "BLT_5gv", "BLT_5tv", "BLT_6tv", "BLT4_2g",  "BLT4_2u",  "BLT4_5t",
                                 "C0_2g",   "C0_5t",   "C0_2u",   "C0_2g_rs",
                                 "HL_2gc",  "HL_2gs",  "HL_2gvm", "HL_2gvp",  "HL_2gv",   "HL_2uv",
                                 "HL_5tv",  "HLt_2gc", "HL4_2g",  "HL4_2u",   "HL4_5t",   "HL4t_2g", 
                                 "MEM_s",   "MEM_v",
                                 "MBWC_2gc","MBWC_2gs","MBWC_2gv","MBWC_2gvm","MBWC_2gvp","MBWC_2uv",
                                 "MBWC_5tv", 
                                 "MBWC4_2g","MBWC4_2u","MBWC4_5t",
                                 "Y_2g",    "Y_2u",    "Y_5t",
                                 "BLT_28s", "BLT_28v", "Y_28"],
                    "file_suffix":".dyn",
                    "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                    "tests":None,
                    "run_validation_suffix":".hsp",
                    "awkfiles":["shell.awk","${prob}.awk"],
                    "awk_commands":[Template("echo " " | ${preawk}awk  -f shell.awk -v sig_dig=${sig} -f ${prob}.awk ")],
                    "exec_command":[Template("$CODE i=${prob}.dyn ")]
                   },
           "SLIDE":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                    "keep_on_pass_file_expr":["answ",".dyn"], 
	            "quicklist":["sslide1k",     "sslide1edgek",  "sslide1k_life",
                                 "sslide2kc",    "sslide2kt",     "sslide2edgekt",
                                 "sslide3l",     "sslide3p",      "sslide3l_frl",  "sslide3p_frl",
                                 "sslide3p_life","sslide3l_self", "sslide3pn",     "sslide3tl",
                                 "sslide3p_damp","sslide3edgep",  "sslide3edgel",  "sslide3edgetl",
                                 "sslidets3p",   "sslidets3l",
                                 "sslide5l",     "sslide5p",      "sslide5p_frl",  "sslide5pn",
                                 "sslide5p_damp",
                                 "sslide6k",     "sslide7k",
                                 "sslide8p",     "sslide8pn",     "sslide8rot_p",  "sslide8rot_pn",
                                 "sslide9ps",    "sslide9pt",     "sslide9pt_sf",  "sslide9psn",
                                 "sslide9ptn",   "sslide9ps_frl", "sslide9ps_damp","sslide9edgept",
                                 "sslide9rot_p", "sslide9rot_pn",
                                 "sslide10lr",   "sslide10psl",   "sslide10lsl",
                                 "sslide10pv",   "sslide10pvn",   "sslide10psl_damp",
                                 "sslide12l",    "sslide12p",     "sslide12l_vec", "sslide12pn",
                                 "sslide12p_vec",                 "sslide5_12l",   "sslide5_12p",
                                 "sslide12p_vecn",                "sslide12ind_p", "sslide12ball_l",
                                 "sslide12ind_l","sslide12l_frl", "sslide12p_frl", "sslide12l_mfric",
                                 "sslide12p_mfric",               "sslide12p_damp","sslide12l_tri",
                                 "sslidets12p",  "sslidets12l",
                                 "sslide14ball_l",                "sslide14l_frl", "sslide14p_frl",
                                 "sslide14p_mfric",
                                 "sslide15p",    "sslide15l",     "sslide15l_frl", "sslide15p_frl",
                                 "sslide15p_damp",
                                 "sslide16p",    "sslide16l",     "sslide16pe",    "sslide16le",
                                 "sslide16l_frl","sslide16p_frl", "sslide16ps",    "sslide16ps2",
                                 "sslide16pt",   "sslide16pt2",   "sslide16ptied", "sslide16psl",
                                 "sslide16lsl",  "sslide16p_damp","sslide16psl_damp","sslide16ptied_damp",
                                 "sslide17kc",   "sslide17kt",
                                 "sslide18p",    "sslide18l",     "sslide18ps",    "sslide18ps2",
                                 "sslide18pt",   "sslide18pt2",   "sslide18p_damp", 
                                 "sslidemulti",  "ssliderigid",
                                 "init_slide3l",   "init_slide3p",   "init_slide10l",      "init_slide10p",
                                 "init_slide12l",  "init_slide12p",  "init_slide12l_ball", "init_slide12p_ball",
                                 "init_slide14l",  "init_slide14p",  "init_slide14l_ball", "init_slide14p_ball",
                                 "init_slide15l",  "init_slide15p",
                                 "init_slide16l",  "init_slide16p",  "init_slide16l_sl", "init_slide16p_sl",
                                 "init_slide18l",  "init_slide18p"],
                    "file_suffix":".dyn",
                    "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                    "tests":None,
                    "run_validation_suffix":".hsp",
                    "awkfiles":["slide.awk","${prob}.awk"],
                    "awk_commands":[Template("echo " " | ${preawk}awk  -f slide.awk -v sig_dig=${sig} -f ${prob}.awk ")],
                    "exec_command":[Template("$CODE i=${prob}.dyn ")]
                   },
           "TPLATE":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                     "keep_on_pass_file_expr":["answ",".dyn"], 
	             "quicklist":["tplate1",     "tplate1u",      "tplate2",     "tplate2i",
                                  "tplate3",     "tplate4",
                                  "tplate12",    "tplate15",      "tplate18",    "tplate19",
                                  "tplate21",    "tplate21i",     "tplate22",    "tplate22i",
                                  "tplate23",    "tplate23i",     "tplate24",
                                  "tplate30",    "tplate33",      "tplate33i",   "tplate34",
                                  "tplate35",
                                  "tplate38",    "tplate39",      "tplate41",
                                  "tplate46",    "tplate46i",     "tplate52",    "tplate54",
                                  "tplate71",    "tplate74",      "tplate74i"],
                     "file_suffix":".dyn",
                     "tests":None,
                     "run_validation_suffix":".hsp",
                     "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                     "awkfiles":["tplate.awk"],
                     "awk_commands":[Template("${preawk}awk -f tplate.awk -v sig_dig=${sig} ${prob}.hsp")],
                     "exec_command":[Template("$CODE i=${prob}.dyn ")]
                   },
           "THICKSHELL":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                      "keep_on_pass_file_expr":["answ",".dyn"], 
                      "quicklist":["tbasic1", "tshell_m52_frac"],
                      "file_suffix":".dyn",
                      "tests":None,
                      "run_validation_suffix":".hsp",
                      "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                      "awkfiles":["${prob}.awk"],
                      "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")],
                      "exec_command":[Template("$CODE i=${prob}.dyn ")]
                   },
           "XFEM":{"keep_on_fail_file_expr":[".elem", "hsp", "plt",".dyn"],
                   "keep_on_pass_file_expr":["answ",".dyn"], 
                   "quicklist":["plate_frac", "tube_frac"],
                   "file_suffix":".dyn",
                   "run_validation_suffix":".hsp",
                   "default_tolerances":{"type":"rel","tolerance":"1.0e-03"},
                   "tests":None,
                   "awkfiles":["${prob}.awk"],
                   "awk_commands":[Template("${preawk}awk -f ${prob}.awk -v sig_dig=${sig} ${prob}.hsp")],
                   "exec_command":[Template("$CODE i=${prob}.dyn ")]
                   }
                }
		   
